version: "3.9"
services:
  app:
    build:
      context: .
      args:
        - MIX_API_BASE_URL=http://localhost:8000/api
    ports:
      - "8000:8000"
    environment:
      - "APP_NAME=HansForms"
      - "APP_ENV=local"
      - "APP_KEY=base64:7sPx7H8snxeKWCrCOecbr4qNMrwqYScq76cKM2+sWME="
      - "APP_DEBUG=true"
      - "APP_URL=http://localhost:8000"
      - "LOG_CHANNEL=stack"
      - "LOG_LEVEL=debug"
      - "DB_CONNECTION=pgsql"
      - "DB_HOST=postgres"
      - "DB_PORT=5432"
      - "DB_DATABASE=laravel"
      - "DB_USERNAME=postgres"
      - "DB_PASSWORD=toor"
      - "MAIL_MAILER=smtp"
      - "MAIL_HOST=mailhog"
      - "MAIL_PORT=1025"
      - "MAIL_USERNAME=null"
      - "MAIL_PASSWORD=null"
      - "MAIL_ENCRYPTION=null"
      - "MAIL_FROM_ADDRESS=null"
      - "MAIL_FROM_NAME=HansForms"
      - "SANCTUM_STATEFUL_DOMAINS=localhost,localhost:8000,127.0.0.1:8000"
      - "SESSION_DRIVER=cookie"
      - "APP_TIMEZONE=Europe/Prague"
      - "SESSION_LIFETIME=14400"
      - "PRIVATE_FORM_BASE_URL=http://localhost:8000"
    depends_on:
      - "postgres"
  
  postgres:
    image: "postgres:15-alpine"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=toor"
      - "POSTGRES_DB=laravel"
    ports:
      - "5433:5432"